name: Deploy to Fly
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy_backends:
    name: Deploy back-end(s) (flyctl)
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd backend && flyctl deploy --remote-only && cd ../backup_ms/backend && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy_backup_frontend:
    runs-on: ubuntu-latest
    name: Deploy backup front-end (wrangler-cli)
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd backup_ms/frontend && npm install

      - name: Build
        run: cd backup_ms/frontend && npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish backup_ms/frontend/dist --env production --project-name backup-ms
