name: Frontend CI

on: pull_request

jobs:
  tests:
    name: Tests and linters
    runs-on: ubuntu-latest   
    defaults:
      run:
        working-directory: frontend 
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - uses: stefanoeb/eslint-action@1.0.2