name: Frontend CI

on: pull_request

jobs:
  lint_front:
    name: Lint front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
  lint_back:
    name: Lint back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
